#!/bin/bash

export PATH="$HOME/models/vllm/.venv/bin:$PATH"
unset VLLM_DISABLED_KERNELS
export VLLM_IFACE=enp1s0f0np0
export NCCL_SOCKET_IFNAME=$VLLM_IFACE
export GLOO_SOCKET_IFNAME=$VLLM_IFACE
export NCCL_IB_HCA=rocep1s0f0
export NCCL_IB_DISABLE=0
export VLLM_HOST_IP=169.254.195.229
export VLLM_TRITON_MLA_SPARSE_ALLOW_CUDAGRAPH=${VLLM_TRITON_MLA_SPARSE_ALLOW_CUDAGRAPH:-0}
export VLLM_TRITON_MLA_SPARSE_MATMUL_DECODE=${VLLM_TRITON_MLA_SPARSE_MATMUL_DECODE:-1}
export VLLM_USE_RAY_COMPILED_DAG_OVERLAP_COMM=${VLLM_USE_RAY_COMPILED_DAG_OVERLAP_COMM:-1}
export RAY_memory_usage_threshold=0.99


ray stop -f || true
ray start \
    --head \
    --node-ip-address=169.254.195.229 \
    --port=6379
